### ISSUE TITLE
Number of tango 

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#47]
Can you hide the number of tango income (over the tango tower) from the opposing team.
I think it will add more intrigue into the game.

**Comment by Avi3ndha** [comment]
I think the easiest way to accomplish this would just be to put permanent fog of war over everything except the 4 lanes and the lane leading to king.  The question would be to have this fog on regardless of whether people vote fog of war or not?

But I agree that it would make it a bit more interesting since you'd have no true way to see what the opposing teams' tango income was.  Definitely adds element of surprise if they're saving to overwhelm in the later levels.

**Comment by Dizzy76** [comment]
Your idea is better than mine. =)
But in your case you should also hide all upgrades of the king.
The opposing team must see only line of hit points without any numbers.

**Comment by Avi3ndha** [comment]
I think leaving the king visible isn't a bad thing. It only gives a rough idea of what people have saved in tangos. I've watched a "win" turn around because someone was saving and forced to use to save the round. That doesn't necessarily give away what tango income is. There are a few people left that save from round one (even though that doesn't translate to being better in the long run). Which is another anomaly that deserves to be fixed for random players.

**Comment by Dizzy76** [comment]
Hiding the upgrades of the king is the most important idea.
For example:
Wave 21 or 23
I dont know what to do pushing or not coz i have no idea  enemy's king  has been upgraded or not.

**Comment by n-gao** [comment]
tango income of enemies isnt visible anymore
