### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#64]
Three tabs of highscores (**won games**, **kills** and **earned tango**)  have not been updated for more than 10 days.
With **experience** there is no problem.

**Comment by jonaswox** [comment]
Also, I think the metrics of the 4 public stats are kind of bad. 

It is all grinder metrics; wins, experience, earned tangos, kills. 

Instead what we really would want is win/loss ratio, 

because right now, only way to get on the leaderboard is to play alot, and not to play good.

**Comment by Dizzy76** [comment]
Exactly
Im sure it will do the game more popular.
But in highscores must be only players who have played more than 300 games.

P.S. After recent updates player count has increased from 200-250 to 300-370.

**Comment by Dizzy76** [comment]
There is another opinion
Let it be as it is but experience will be count only when player win the game.
But in this case current experience should be recalculated.

**Comment by n-gao** [comment]
Unfortunately statistics can not be recalculated. Since it was my first Web API I made a few very unsmart design decisions there. Most changes would need to reset all statistics which I want to avoid

**Comment by Dizzy76** [comment]
Sometimes it's better to start from the beginning and do well

**Comment by n-gao** [comment]
I guess most players wont appreciate their stats reseted so I wont do it.

**Comment by Dizzy76** [comment]
What is your point?
Let it be as it is?

**Comment by n-gao** [comment]
I would love to rewrite the server in a appropriate way. But I do not want to lose all player data (and player do not want this either) and I do not have the time to do so, since Legion TD is just a leisure project of mine. I am getting literally nothing for my hours of working for this game (actually I am paying for a rented server which hosts your statistics) so I have to limit my resources spend on this project. 

So it is not worth spending so much time recoding the server which would erase all data.

**Comment by Dizzy76** [comment]
I understand you. 
no problems

**Comment by jonaswox** [comment]
I totally understand as well. No pressure. 

With that said, Im one of those players, and the current state of the system is just useless anyway - so I wouldnt mind. 

I does not update the highscore list - For example, my earned tangos is greater than most of the top15 list, and im not there - I guess im not the only one =)

**Comment by Dizzy76** [comment]
I talked with most of top 15 list and they have same opinion with jonaswox
and now for new player is impossible to get in highscore

**Comment by jonaswox** [comment]
Im sorry, its just because I dont understand. 

Is it because you didnt code a persistancy layer or why does all stats need to be reset to change the servercode?

**Comment by n-gao** [comment]
Currently working on a new server, which hopefully performs better and allows more advanced statistics. I also plan to implement a new ranking.

**Comment by Dizzy76** [comment]
Very very nice to hear that
May the Force be with you =)

**Comment by Dizzy76** [comment]
Can you reveal the secret of how the new ranking will work?

**Comment by n-gao** [comment]
Since I am not able to create a matchmaking the system will work as follows:
Every player starts at  a certain rating. With each victory your rating increased. The amount which you get or lose is determined by the difference of ratings in your game. For example: When you have a low rating and you win against a team where every player has a high rating, your rating will increase more than when win against a team whose ratings are lower than yours.

**Comment by jonaswox** [comment]
such cool news!

**Comment by n-gao** [comment]
new server is nearly ready. Sadly there is no way to transfer the old data

**Comment by jonaswox** [comment]
Its a shame, but overall its very positive update!!!!

**Comment by n-gao** [comment]
the new model is more versatile and should allow more modifications. I hope I get it only today.

**Comment by n-gao** [comment]
it is online.

**Comment by n-gao** [comment]
Please suggest more features regarding statistics.
