### ISSUE TITLE
fog of war

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#67]
Can You rework fog of war?
Make visible only small area around the wave units.
In this case the opposing team has a possibility to see the enemy king and enemy towers only when they are under attack.
It adds intrigue to the game because the opposing team cant see updates of king, rotation speed of tango tower and camp of income units.

**Comment by Dizzy76** [comment]
Roofkiller, Should I continue? Or you stopped supporting the project?

**Comment by n-gao** [comment]
For the moment I need a break due to private reasons. I guess I will continue to work on this project in the future but I can not promise anything. If you continue to report bugs and make suggestions it is more likely that I will implement them in the future.
If you want to take part in the development of this mod, you are warmly invited.

**Comment by Dizzy76** [comment]
is it possible to implement this idea?

**Comment by n-gao** [comment]
Could be done, sadly I have no time to do this. But I will keep this open for future updates.

**Comment by Laika9876** [comment]
When can you continue the development of custom?

**Comment by n-gao** [comment]
Do not know whether I can keep develop this. Maybe in 3 months.
